### ISSUE TITLE
plugin/route53 CoreDNS fails to start when API throttling occurs

### ISSUE THREAD

**Issue by rnsc** [miekg/coredns#4899]
**What happened**:
Tried to start two instances of CoreDNS with the same AWS Route53 zones configured.
CoreDNS failed to start on both instances because they ate each other's request allocation on the AWS API.
Throttling kicks in and results in plugins failing.

**What you expected to happen**:
I would expect CoreDNS to at least retry recoverable errors on the AWS HTTP API instead of failing at the first error.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce this, you'll need a good amount of hosted zones (> 200) on AWS Route53 and start multiple instances of CoreDNS with that config.

This docker compose file is sufficient:
```yaml
---
version: '3'

services:
  dns_one: &route53
    image: coredns
    volumes:
      - $PWD/conf:/etc/coredns
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    restart: always
  dns_two: *route53
```

CoreDNS was built with the following Dockerfile:

```raw
FROM golang:1.16 as build_stage

RUN mkdir /v
ADD coredns /v

WORKDIR /v

RUN make

FROM scratch

COPY --from=build_stage /v/coredns /

CMD ["/coredns", "-conf", "/etc/coredns/Corefile"]
```

**Anything else we need to know?**:
I did some update to the route53 plugin to overcome this issue on my local setup by adding a MaxRetries value to the AWS session.
I can provide a PR if you want to discuss it.

**Environment**:

- the version of CoreDNS: CoreDNS-1.8.5
- Corefile: N/A
- logs, if applicable: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Others: N/A
