### ISSUE TITLE
Lookups failing from zone file after upgrade to 1.8.5

### ISSUE THREAD

**Issue by Hitman247m** [miekg/coredns#5092]
**What happened**: I've been running CoreDNS using the official docker container, and everything was working correctly until I attempted to upgrade to either 1.8.5 or 1.8.6. The container runs correctly, and continues to forward upstream queries, but all lookups for zones defined in RFC 1035-style master files always return `NXDOMAIN`. If I revert to 1.8.4, the queries are successful again.

**What you expected to happen**: DNS query should return the record defined in the `zones/db.dc.example.com` file, rather than `NXDOMAIN`

**How to reproduce it (as minimally and precisely as possible)**: Use the docker compose shown below:
```yaml
version: '2.4'

services:

  coredns-test:
    container_name: coredns-test
    image: coredns/coredns:1.8.6
    restart: 'unless-stopped'
    entrypoint: ["/coredns"]
    command: ["-conf", "/etc/coredns/Corefile"]
    mem_limit: 256m
    expose:
      - '53'
      - '53/udp'
      - '9253'
    ports:
      - "20053:53/tcp"
      - "20053:53/udp"
    volumes:
      - '/tmp/coredns/test_conf:/etc/coredns'
```

**Anything else we need to know?**: N/A

**Environment**:

- CoreDNS Version: 1.8.6 (broken), 1.8.5 (broken), 1.8.4 (working correctly), 
- Corefile:
```
(global) {
    log
    errors
    reload 10s
}

. {
    import global
    auto {
        directory /etc/coredns/zones
        reload 10s
    }
    forward . 8.8.8.8:53 {
        health_check 10s
    }
    cache 30
}
```

- Zonefile (`db.dc.example.com`):
```
$ORIGIN dc.example.com.
@       3600 IN SOA ns1.example.com. admin.example.com. (
                                2017042745 ; serial
                                7200       ; refresh (2 hours)
                                3600       ; retry (1 hour)
                                1209600    ; expire (2 weeks)
                                3600       ; minimum (1 hour)
                                )

        3600 IN NS ns1.example.com.
        3600 IN NS ns2.example.com.

test	        IN A	 10.100.0.011
```

- logs, if applicable:
```
[INFO] plugin/auto: Inserting zone `dc.example.com.' from: /etc/coredns/zones/db.dc.example.com
.:53
[INFO] plugin/reload: Running configuration MD5 = 34635d1a112dbe134fbd10a8c69974ef
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[INFO] 10.0.20.211:60336 - 6239 "A IN test.dc.example.com. udp 48 false 4096" NXDOMAIN qr,aa,rd 119 0.000149983s
```

- OS (e.g: `cat /etc/os-release`):
```
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8
```

- Others: N/A
