### ISSUE TITLE
Support IRSA in Route53 plugin

### ISSUE THREAD

**Issue by yuha0** [miekg/coredns#5153]
Apologize in advance if this is some user end config error that I fail to recognize.

I am trying to configure coredns to read records in some route53 private zone. My preference is to use IRSA so that I don't need to create static AWS access keys, but it doesn't work. My setup:

in coredns config:

```yaml
example.com:53 {
  route53 example.com:<my-private-zone-id>
}
```

And I have verified that the web identity token has been injected into the container successfully:

```yaml
  containers:
    env:
    - name: AWS_DEFAULT_REGION
      value: us-east-2
    - name: AWS_REGION
      value: us-east-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::<arn-for-the-role>
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: 602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/coredns:v1.8.4-eksbuild.1
...
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kr77q
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
...
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```

However, in the log, I found that coredns is still trying to use the instance profile:

```
plugin/route53: /etc/coredns/Corefile:26 - Error during parsing: failed to create route53 plugin: AccessDenied: User: arn:aws:sts::<aws-account-id>:assumed-role/eks-worker-<eks-cluster-name>/i-<ec2-instance-id> is not authorized to perform: route53:ListHostedZonesByName because no identity-based policy allows the route53:ListHostedZonesByName action
        status code: 403, request id: xxxxxxxxxxxxxxxxxxxxxxxxx
```

**What would you like to be added**:

Support for IRSA, or, if it is already supported, update the documentation to include instruction on how to use it.

**Why is this needed**:

Provision static AWS access keys, as suggested in the documentation, is a security risk. Using instance profile is doable, but provision a dedicated node group just for a a few coredns pods in our k8s clusters seems to be a little overkill and can create management overhead. 

If it is possible to support IRSA, we can grant Route53 read permission to coredns' service account and nothing else.
