### ISSUE TITLE
The  latest version,  it can't connect to coredns's port like 53  from pod in the cluster.

### ISSUE THREAD

**Issue by ijiaojian** [miekg/coredns#5391]
At first, I deploy the coredns 1.9.2 in k8s,  all service , deployment, pod is running rightly,  coredns serviceIP: 192.168.0.2, but when I telnet  port(53) in the busybox pod, I got  
"/ # telnet 192.168.0.2 53 
  /#  telnet: can't connect to remote host (192.168.0.2): Connection refuse
"
then I tried ping the ip 192.168.0.2  on the work node,  I got the successful response.

these confused me,  because coredns(every pod , service ) was  running rightly,  I tried reinstall the coredns, but it didn't work.

At last,  I reinstalled it with version 1.8.3, it works. so  is there something especially where the latest version ?

k8s version: 1.24.0

**Comment by chrisohaver** [comment]
What steps to you take when reinstalling coredns?

**Comment by ijiaojian** [comment]
@chrisohaver 

I just deleted the service and deployment,  then editing the yaml generated by "deploy.sh", changed the version from 1.9.2 to 1.8.3,  like this below:

```
-----the fragment in Deployment----
containers:
      - name: coredns
        image: coredns/coredns:1.8.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
```
