### ISSUE TITLE
coredns pods don't wait for lameduck duration before shutting down (coredns v1.8.3 on EKS v1.20)

### ISSUE THREAD

**Issue by connorworkman** [miekg/coredns#5409]
**What happened**:
When issuing a rolling restart to our coredns v1.8.3 deployment, coredns  shuts down before the lameduck duration (21s) has passed, resulting in failed (timed out) DNS lookups across the cluster (AWS EKS 1.20). Our readiness probe executes every 10s, with a failureThreshold of 2.

Logs:
```
May 26, 2022 @ 16:04:57.777 [INFO] plugin/health: Going into lameduck mode for 21s
May 26, 2022 @ 16:04:57.777 [INFO] SIGTERM: Shutting down servers then terminating
```

**What you expected to happen**:
It's my understanding that the coredns service should not shutdown until the lameduck duration has passed. Thus, we have no way to do a graceful rescheduling of any coredns pod without DNS service outages. We need the readiness probe to fail so that the pod can be removed from the service endpoint (and propagate this change to kube-proxy/AWS CNI) prior to the pod's shutdown.

**How to reproduce it (as minimally and precisely as possible)**:
Launch an EKS cluster v1.20 with coredns v1.8.3, join worker nodes, set coredns config and update readiness probe to match the provided environment. Delete one of the coredns pods via kubectl. The pod claims to go into lameduck mode but coredns immediately shuts down and the pod is terminated before the readiness probe reaches the failure threshold, before the pod is removed from the coredns service endpoint.

**Environment**:

- the version of CoreDNS: 1.8.3
- Corefile:
```
    .:53 {
        errors
        health {
          lameduck 21s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
May 26, 2022 @ 16:04:57.777[INFO] plugin/health: Going into lameduck mode for 21s
May 26, 2022 @ 16:04:57.777 [INFO] SIGTERM: Shutting down servers then terminating

- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Others:
coredns deployment readinessProbe:
```
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```

**Comment by chrisohaver** [comment]
> .. coredns shuts down before the lameduck duration (21s) has passed, ...

I was unable to reproduce this. I tested in a kind cluster k8s 1.21.1.  When terminating a pod with `kubectl delete`, the pod remained in a terminating state for the duration of the 21 seconds.

> We need the readiness probe to fail so that the pod can be removed from the service endpoint ...

When a pod is administratively deleted, the corresponding service's endpoints are immediately updated to not include the deleted pod ip. So no new requests will get routed to the terminating pod. This happens actively on deletion, not reactively as a result of failed readiness checks.

Lameduck mode is in place to give a chance for upstream requests to return and be sent to clients that made requests prior to the pod being deleted. Anything longer than 5 seconds is not likely to be useful in this context, since most clients time out waiting for a response after 5 seconds.

**Comment by connorworkman** [comment]
> I was unable to reproduce this. I tested in a kind cluster k8s 1.21.1. When terminating a pod with kubectl delete, the pod remained in a terminating state for the duration of the 21 seconds.

Spent today testing this again after upgrading one of the clusters to EKS 1.22 and coreDNS 1.8.7.
It seems to work for me with coredns 1.8.7.

It definitely does not seem to respect the lameduck duration in 1.8.3 with EKS 1.20...
Here is a timed deletion of a coredns 1.8.3 pod in EKS 1.20, with a lameduck duration of 121s:
```
% time devkubectl delete pod -n kube-system coredns-56dbcfbc4f-pb7z5
pod "coredns-56dbcfbc4f-pb7z5" deleted
kubectl --kubeconfig ~/.kube/conf.d/devkubeconfig delete pod -n kube-system   0.59s user 0.24s system 2% cpu 36.920 total
```
What version of coredns did you try to reproduce with?

Unfortunately on 1.8.7 I still consistently see timeouts when deleting coredns pods even though lameduck is now working as expected. I'm just using a temporary shell container within the cluster to test that:

```
bash-5.1# for i in {1..100000} ; do sleep .3 ; dig +time=1 +tries=1 +short kafka-headless.cicd.svc.cluster.local | grep -v 10.1 ; done

;; connection timed out; no servers could be reached

;; connection timed out; no servers could be reached

;; connection timed out; no servers could be reached
```


> When a pod is administratively deleted, the corresponding service's endpoints are immediately updated to not include the deleted pod ip. So no new requests will get routed to the terminating pod. This happens actively on deletion, not reactively as a result of failed readiness checks.

This is helpful, I guess that explains why readiness probes don't seem to be evaluated during termination.
As I understand it, the service endpoint change needs time to propagate to kube-proxy and the CNI on other nodes, so I was hoping/thinking a longer duration might stop the timeouts from happening.

**Comment by chrisohaver** [comment]
> What version of coredns did you try to reproduce with?

I tested 1.8.3, and a couple of other versions in a kind 1.22 cluster.  All appear to wait for the lameduck duration before terminating.

> Unfortunately on 1.8.7 I still consistently see timeouts when deleting coredns pods

How many replicas of coredns do you have? How many do you delete at a time?

> we have no way to do a graceful rescheduling of any coredns pod 

Can you elaborate on what these rescheduling operations entail?  And how you perform them (e.g. what commands).

> As I understand it, the service endpoint change needs time to propagate to kube-proxy and the CNI on other nodes, so I was hoping/thinking a longer duration might stop the timeouts from happening.

I checked the timing of the shutdown events, and verified that the dns listeners are shut down _after_ the lameduck wait.  So, in theory if kube-proxy can lag behind, CoreDNS in the lameduck state can still receive and answer queries.

**Comment by connorworkman** [comment]
> How many replicas of coredns do you have? How many do you delete at a time?

In this example 8 replicas.  Just deleting one pod seems to be enough to cause DNS timeouts for a few seconds.

> Can you elaborate on what these rescheduling operations entail? And how you perform them (e.g. what commands).

Yeah, so for example to upgrade EKS we have to replace all of our worker nodes, which means we require that the coredns pods are able to move to new nodes without causing DNS failures. In that type of scenario, they're evicted one at a time similar to deleting a single pod.

The other scenario is if we want to change coredns deployment specs i.e. CPU or memory requests/limits (or if we just want to restart the deployment for some reason). In that scenario, it should be equivalent to a rollout restart i.e. `kubectl rollout restart deployments/coredns -n kube-system` where the update strategy is:

```
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

With this update strategy the new pods become ready _very_ quickly, so all 8 replicas are replaced within a few (0 to 10) seconds:

```
% kubectl get pods -n kube-system -l k8s-app=kube-dns
NAME                      READY   STATUS    RESTARTS   AGE
coredns-55b9c7c66-c4xk5                             1/1     Terminating        0                90m
coredns-55b9c7c66-cjfbk                             1/1     Terminating        0                90m
coredns-55b9c7c66-g8bpn                             1/1     Terminating        0                90m
coredns-55b9c7c66-gfv26                             1/1     Terminating        0                90m
coredns-55b9c7c66-j4q5r                             1/1     Terminating        0                3m42s
coredns-55b9c7c66-kg4kb                             1/1     Terminating        0                90m
coredns-55b9c7c66-lsccp                             1/1     Terminating        0                90m
coredns-55b9c7c66-qrpqb                             1/1     Terminating        0                90m
coredns-58686f7f6-26h7m                             1/1     Running            0                11s
coredns-58686f7f6-5jvmt                             1/1     Running            0                12s
coredns-58686f7f6-bl59n                             1/1     Running            0                15s
coredns-58686f7f6-kpg52                             1/1     Running            0                9s
coredns-58686f7f6-ngjmz                             1/1     Running            0                15s
coredns-58686f7f6-p5wlw                             1/1     Running            0                9s
coredns-58686f7f6-s27q2                             1/1     Running            0                14s
coredns-58686f7f6-x2vwl                             1/1     Running            0                12s
```

Here's the full deployment spec (on the coredns 1.8.7 + EKS 1.22 example) just in case:

```
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 8
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-06-06T14:50:13-05:00"
      creationTimestamp: null
      labels:
        eks.amazonaws.com/component: coredns
        k8s-app: kube-dns
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.8.7-eksbuild.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          procMount: Default
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
      dnsPolicy: Default
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: coredns
      serviceAccountName: coredns
      terminationGracePeriodSeconds: 130
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns
        name: config-volume
```
