### ISSUE TITLE
when lameduck and config-reload are enabled, editing the config causes all pods in the deployment to go unready

### ISSUE THREAD

**Issue by connorworkman** [miekg/coredns#5471]
I'm submitting this as a question instead of a bug since it might be the intended behavior but it seems undesirable.
Is this the expected behavior? Any advice on how to avoid a total service outage when updating the configmap?

**What happened**:
Editing the coredns configmap, when lameduck is enabled, causes all pods in the deployment to go unready during config reload.

**What you expected to happen**:
Config reload should occur without entering lameduck mode if possible, as there's no guarantee that pods will reload config one at a time.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a coredns deployment with lameduck mode and readiness/liveness probes.
Edit the configmap (i.e. change lameduck duration from 21s to 22s) and wait for config reload to trigger.
Observe that pods fail readiness probe until lameduck mode ends, causing total service outage.

**Environment**:

- the version of CoreDNS: 1.8.7
- Corefile:
```
    .:53 {
        log . {
          class denial
          class error
        }
        errors
        health {
          lameduck 22s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

- logs, if applicable:
```
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 21s
...
[INFO] plugin/reload: Running configuration MD5 = 2f64ae2f830ad4fa527721f112bb527f
[INFO] Reloading complete
```

- OS (e.g: `cat /etc/os-release`):
Amazon Linux 2 Karoo

- Probe configuration:
```
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
