### ISSUE TITLE
Issue with SOA requests

### ISSUE THREAD

**Issue by albertkohl-monotek** [miekg/coredns#5557]
**What happened**:
when running SOA reqeusts, i get SERVFAIL errors

**What you expected to happen**:
first off, forgive me if i'm missing anything, or am supplying unhelpful info, i'm fairly new, and self-taught at k8s.

i just redeployed a working cluster (using ansible) and i started having issues with certificates approving from cert-manager. (via dns01 challenge) after digging, i pinned it down to what appears to be an dns issue with core dns. 

**How to reproduce it (as minimally and precisely as possible)**:
install microk8s (#>  sudo snap install microk8s --classic --channel 1.24 )
install coredns snap plugin (uses version 1.9.0 according to their git) (#> sudo microk8s enable dns)
deploy a dnsutils pod:

 ```
cat <<EOF | microk8s.kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
EOF
```

shell into dnsutils pod: (#>microk8s.kubectl exec -it dnsutils -- /bin/sh)
run nslookup and check soa:
(#> nslookup
set type=soa
google.com

*** Can't find google.com: No answer)

now edit your deployment (#> microk8s.kubectl edit deployment.apps/coredns)
and change the image to 1.8.0, do the dns test again, and it will return correctly:

Server:         10.152.183.10
Address:        10.152.183.10#53

cluster.local
        origin = ns.dns.cluster.local
        mail addr = hostmaster.cluster.local
        serial = 1659844218
        refresh = 7200
        retry = 1800
        expire = 86400
        minimum = 5

**Anything else we need to know?**:

**Environment**:
microk8s on ubuntu 20

- the version of CoreDNS: 1.9.0
- Corefile: default
