### ISSUE TITLE
CoreDNS does not work for MailU Setup

### ISSUE THREAD

**Issue by entrymon** [miekg/coredns#5826]
**What happened**:
While using latest kubernetes i.e 1.25.x++ if you install mailu using helm chart, we noticed that one of pod does not spin up complaining Core DNS Issue

```CRITICAL:root:Your DNS resolver at 10.96.0.10 isn't doing DNSSEC validation;```

MailU refers to this as core DNS bug in FAQ - Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.

**What you expected to happen**:
Spin up pods as expected.

**How to reproduce it (as minimally and precisely as possible)**:
minikube start
helm repo add mailu https://mailu.github.io/helm-charts/
helm repo update
helm upgrade --install mailu mailu/mailu -f values.yaml

Sample values as below 
```
domain: example.com
hostnames:
- test.example.com
initialAccount:
  domain: mail.example.com
  password: chang3m3!
  username: admin
logLevel: INFO
mail:
  authRatelimit: 100/minute;3600/hour
  messageSizeLimitInMegabytes: 200
secretKey: chang3m3!
ingress.tlsFlavor: letsencrypt
rspamd:
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
```

You may need a certificate issuer depending on your config.
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: test@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: istio
```

**Anything else we need to know?**:

My core dns config map

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.49.1 host.minikube.internal
           fallthrough
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-27T18:26:45Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "18831"
  uid: b0ed46af-4893-4da5-97d6-de7a9eb0502b
```

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
```
kubectl logs -f coredns-565d847f94-5wt6t -n kube-system
.:53
[INFO] plugin/reload: Running configuration SHA512 = 7f038955dae4c38ff683f9cc29be35e782eeae9fa4e4182e72f3e8ea261283b78f2ec654297c5cf9acdb788c237c3e9820c37c05569d5453ac2432c0ff9f9167
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
```

- OS (e.g: `cat /etc/os-release`):
- Others:

```
The admin container won’t start and its log says Critical: your DNS resolver isn't doing DNSSEC validation[](https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation)
Since v1.9, Mailu requires a validating DNSSEC enabled DNS resolver. To check whether your DNS resolver (and its upstream) fits the requirements you can use the following command and see whether the AD flag is present in the reply:

dig @<ip> +adflag example.org A
We recommend that you run your own DNS resolver (enable unbound and update your docker-compose.yml when you update from older versions) instead of relying on publicly available ones. It’s better security-wise (you don’t have to trust them) and RBLs used by rspamd are known to rate-limit per source-ip address.

We have seen a fair amount of support requests related to the following:

dnsmasq won’t forward DNSSEC results unless instructed to do so. If you are running openwrt or pi-hole, you do need to enable DNSSEC.

[coredns has a bug](https://github.com/coredns/coredns/issues/5189) that we have now worked around

```
