### ISSUE TITLE
Docker working directory changed

### ISSUE THREAD

**Issue by izenn** [miekg/coredns#6249]
Upgraded from 1.10.1 to 1.11.0 and coredns was not reading the config from /Corefile or /hosts anymore

steps to reproduce:
deploy docker image with volume mounts to /Corefile and /hosts

per docker inspect, the working directory for the docker container was changed from / to /home/nonroot

using coredns/coredns:latest from hub.docker.com

**Comment by NikVandewouwer** [comment]
Not sure if related, but also for me coredns started crashing this morning after pulling latest (1.11.0) due latest tag:
```
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    volumes:
      - ${ROOT_DIR}/docker/coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
    expose:
      - 53
      - 53/udp
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped
```

 I've received continuously the following error in the logs every minute:
`Listen: listen tcp :53: bind: permission denied`

After reverting back to 1.10.1 everything works again:
```
  coredns:
    image: coredns/coredns:1.10.1
    container_name: coredns
    volumes:
      - ${ROOT_DIR}/docker/coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
    expose:
      - 53
      - 53/udp
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped
```

(I'm using docker-compose on synology nas)

**Comment by SuperQ** [comment]
I'm guessing this is related to the user ID change.

https://github.com/coredns/coredns/pull/5969

**Comment by NikVandewouwer** [comment]
@SuperQ could you guide me in the right direction what to do to able to run 1.11.0?

**Comment by chrisohaver** [comment]
@NikVandewouwer, Try adding NET_BIND_SERVICE capability

**Comment by chrisohaver** [comment]
> @NikVandewouwer, Try adding NET_BIND_SERVICE capability

Nevermind - I was thinking this was a privileged port bind issue, not a directory issue.  I wasn't paying attention.

**Comment by chrisohaver** [comment]
> > @NikVandewouwer, Try adding NET_BIND_SERVICE capability
> 
> Nevermind - I was thinking this was a privileged port bind issue, not a directory issue. I wasn't paying attention.

OK, I see there are two issue reported here. Second is a port bind issue: `Listen: listen tcp :53: bind: permission denied`
Adding NET_BIND_SERVICE capability should resolve that.

**Comment by NikVandewouwer** [comment]
@chrisohaver how would I update my docker-compose to add NET_BIND_SERVICE ? The documentation I find is mainly around k8s.

This for example leads to the same error
```
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${ROOT_DIR}/docker/coredns:/etc/coredns
    command: -conf /etc/coredns/Corefile
    expose:
      - 53
      - 53/udp
    ports:
      - 53:53
      - 53:53/udp
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
```

**Comment by chrisohaver** [comment]
I dont know off hand.
Alternately, you could try binding to an alternate port in the container (eg 5353), mapping it to the exposed 53 port. You’d also need to update corefile to listen to that alternate port.

**Comment by davidgiga1993** [comment]
[This change](https://github.com/coredns/coredns/pull/5969/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R13) in the dockerfile bricked coredns for us. The environment is highly restricted and we're binding coredns on a higher port, however due to the mandatory `cap_net_bind_service` the latest coredns version doesn't start anymore. Allowing this capability isn't an option for us.

Can you please remove that capability from the dockerfile (or create two image variants?). The capability shouldn't be added inside the dockerfile directly.

**Comment by SuperQ** [comment]
You have a highly restricted environment and you use public container images?

**Comment by davidgiga1993** [comment]
> You have a highly restricted environment and you use public container images?

We mirror them and they are being scanned.. this however has nothing to do with my issue :)

**Comment by polarathene** [comment]
**UPDATE:** I have [raised a PR](https://github.com/coredns/coredns/pull/6320) removing the `setcap` change. Unclear at this stage if it would be accepted as it seems the decision may negatively affect one groups needs.

The proper fix would be to have `coredns` request when binding for privileged ports **only** when it's actually needed for the non-root user (_possibly k8s, and with Docker when using host mode networking_). That's a bunch more effort to implement though 🤷‍♂️ 

---

> Allowing this capability isn't an option for us.
> 
> Can you please remove that capability from the dockerfile (or create two image variants?). The capability shouldn't be added inside the dockerfile directly.

~~Could you clarify? Are you running rootless?~~ (_I reproduced with a standard install at rootful daemon_)

Files:

```yaml
# compose.yaml
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    volumes:
      - /tmp/Corefile:/Corefile
    # Restore previous working directory:
    working_dir: /
    # Alternatively direct the command to the custom config location:
    #command: -conf /Corefile
```

```
# Corefile
example.test {
  whoami
}

. {
  forward . 8.8.8.8
}
```

Bring that up with `docker compose up --force-recreate` and get the IP address assigned to it `docker inspect coredns | grep IPAddress` with output such as `172.18.0.2`.

Now you can query it from the host (_or another container on the same container network_):

```bash
# Working whoami for configured domain:
dig @172.18.0.2 example.test | grep '^example'

# Working forward:
dig @172.18.0.2 google.com | grep '^google'
```


I can add the ports and observe no problems in the logs for the container (_in this case the host already had `:53` in use, so I bound to `:54` instead_):

```yaml
    ports:
      - 54:53
      - 54:53/udp
```

Now you can query localhost on port 54:

```bash
# Working whoami for configured domain:
dig @127.0.0.1 -p 54 example.test | grep '^example'

# Working forward:
dig @127.0.0.1 -p 54 google.com | grep '^google'
```

On the test system (_Ubuntu 22.04.3 LTS, fresh VM server install_), running as a non-root user (_but configured for the `docker` group_) there was no issues here requiring capability added, but dropping it would fail:

```yaml
# docker logs coredns
# exec /coredns: operation not permitted
    cap_drop:
      - NET_BIND_SERVICE
```

And as expected that's a non-issue if running the `1.10.1` tag instead of the current `:latest` (`1.11.1`).

---

## Is the `setcap` really meaningful / required?

Dropping the capability requirement (_with `setcap cap_net_bind_service=-ep /coredns`, because I'm too lazy to do a full build_ 😅 ), everything seems to work fine even with `cap_drop` applied and leaving the non-root user.

So the question is what value is that change providing, or am I doing something wrong?

If the user needs to have the capability can't they do so via `cap_add`? (_usually how this is addressed in docker land AFAIK_)

What value is provided by enforcing it on the binary within the container? From what I understand the `setcap` is making the capability requirement explicit, but it doesn't appear required to function, so wouldn't it be wiser to respect the environment?

---

> I've received continuously the following error in the logs every minute:
> `Listen: listen tcp :53: bind: permission denied`
> 
> (I'm using docker-compose on synology nas)

I'm not sure how to reproduce that, but I guess it's due to the host needing that capability enabled? (_or perhaps with your `docker` / `docker compose` binary?_)

I know that Podman at least runs with less default capabilities. I got a different error as shown above when dropping the capability.

**EDIT:** I was able to reproduce that on `1.10.1` by running with a non-root user. On `1.11.1` it should fail with a less helpful error when the capability isn't available, otherwise it should bypass the restriction for unprivileged ports (_which Docker did remove for internal bridges around 2020Q4_).

My guess is it might be due to your kernel as those NAS tend to be quite old, but it could also be the Docker version. I'd add that if you built the image yourself from the `Dockerfile` that without `buildx` / `DOCKER_BUILDKIT=1` the `COPY` directive will lose the capabilities applied to the `coredns` binary. This may also be affected by filesystem / volume driver too 😅
