### ISSUE TITLE
nxdomain when question headless service in k8s.

### ISSUE THREAD

**Issue by brotherlu-xcq** [miekg/coredns#6607]
**What happened**:
curl the headless domain in k8s cluster got `Cloud not resolve host` error.
<img width="889" alt="b9740859-711e-4987-89e0-ca7f4611d30e" src="https://github.com/coredns/coredns/assets/25661357/46fc6c6d-abc9-44b6-a39a-5753b695b090">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
create headless service with below config.
service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
endpointslice:
```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-headless-service
  labels:
    kubernetes.io/service-name: my-headless-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.1.1.1"
    conditions:
      ready: true
      serving: true
      terminating: false
    hostname: test.hostname
    nodeName: test.node.name
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.0
- Corefile: just enabled `fallthrough` in kubernetes plugin.
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others: k8s version: 1.22.7
