### ISSUE TITLE
Route53 Plugin with aws_signing_helper credential-process.

### ISSUE THREAD

**Issue by gowgopal83** [miekg/coredns#6846]
### Discussed in https://github.com/coredns/coredns/discussions/6845

<div type='discussions-op-text'>

<sup>Originally posted by **gowgopal83** August 21, 2024</sup>
Team, 

I am working on enabling the integration between the on-prem coredns(docker on Linux) with Route53. As part of it, the AWS
credentials are defined per the [credential-helper doc](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/credential-helper.html). The helper manages creating a signature with the certificate and calling the endpoint to obtain session credentials; it returns the credentials to the calling process in a standard JSON format for the SDK. We are using a similar setup for the `Spring Boot application,` which is able to obtain the credentials and connect to AWS. 

When using the same approach for the Route53 plugin, I faced a strange error, which I mentioned below.  Any suggestions?

Creds file: 

```
$ ls -l ~/.aws
total 4
-rw-r--r--. 1 dcloud-admin dcloud-admin 534 Aug 21 11:49 config
-rw-r--r--. 1 dcloud-admin dcloud-admin   0 Aug 21 11:55 credentials
$ cat config
[default]
region = us-east-1
credential_process = /opt/iamraw/aws_signing_helper credential-process --certificate /opt/iamraw/mi-07ee124ea66c2.crt --private-key /opt/iamraw/mi-07ee124ea66c2.key --trust-anchor-arn arn:aws:rolesanywhere:us-east-1:<Acc id>:trust-anchor/d5b48e1d-ec20-4eb4-9d17-acf8a6fdadae --profile-arn arn:aws:rolesanywhere:us-east-1:<Acc id>:profile/2fea52ca-2e8e-45e1-bb2a-4d5b0659d4a5 --role-arn arn:aws:iam::<Acc id>:role/phz_role
$ aws sts get-caller-identity
{
    "UserId": "AROAR2ZCZR3C6HPOXV5RT:11c63660d358383a8939163125a09e04",
    "Account": "<Acc id>",
    "Arn": "arn:aws:sts::<Acc id>:assumed-role/phz_role/11c63660d358383a8939163125a09e04"
}
```

Coredns Docker-compose file:

```
version: '3.8'

services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: -conf /etc/coredns/Corefile
    user: root
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./conf:/etc/coredns
      - /home/dcloud-admin/.aws:/root/.aws:ro
    environment:
      - AWS_SDK_LOAD_CONFIG=1
    restart: unless-stopped

networks:
  default:
    driver: bridge
```

CoreFile:
```
.:53 {
    forward . 1.1.1.1 8.8.8.8 1.0.0.1 8.8.4.4 {
      except idev.test.com 15.10.in-addr.arpa dcloud.com 1.10.in-addr.arpa
      prefer_udp
      policy sequential
      health_check 0.5s
    }
    log
    errors
    loadbalance round_robin
    cache 60
    reload 5m
    health
    debug
}

idev.test.com {
    route53 idev.test.com.:<Private_zone_Host-ID> {
      refresh 5m
    }
    header {
        response set ra
    }
    log
    errors
    debug
}

15.10.in-addr.arpa {
    route53 15.10.in-addr.arpa.:<Private_zone_Host-ID> {
      refresh 5m
    }
    log
    errors
}

dcloud.com:53 {
    forward . 10.1.25.101 10.1.25.102
    log
    errors
}

1.10.in-addr.arpa:53 {
    forward . 10.1.125.101 10.1.125.102
    log
    errors
}
```

Error:
```
$ docker-compose logs -f
coredns  | plugin/route53: /etc/coredns/Corefile:24 - Error during parsing: failed to create route53 plugin: ProcessProviderExecutionError: error in credential_process
coredns  | caused by: exec: "sh": executable file not found in $PATH
coredns  | plugin/route53: /etc/coredns/Corefile:24 - Error during parsing: failed to create route53 plugin: ProcessProviderExecutionError: error in credential_process
coredns  | caused by: exec: "sh": executable file not found in $PATH
coredns  | plugin/route53: /etc/coredns/Corefile:24 - Error during parsing: failed to create route53 plugin: ProcessProviderExecutionError: error in credential_process
coredns  | caused by: exec: "sh": executable file not found in $PATH
```</div>
