### ISSUE TITLE
CoreDNS unable to forward to Docker's internal DNS

### ISSUE THREAD

**Issue by RealOrangeOne** [miekg/coredns#7009]
**What happened**:

Since 1.11.4, it's no longer possible to forward to Docker's internal DNS server. 1.11.3 works fine.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
. {
    errors
    log

    forward . 127.0.0.11
}
```

```yaml
services:
  coredns:
    image: coredns/coredns:1.11.4
    container_name: coredns
    volumes:
      - ./Corefile:/home/nonroot/Corefile:ro
    ports:
      - "53054:53/udp"

  coredns_working:
    image: coredns/coredns:1.11.3
    container_name: coredns_working
    volumes:
      - ./Corefile:/home/nonroot/Corefile:ro
    ports:
      - "53053:53/udp"
```

#### Working

```
$ dig coredns @localhost -p 53053 A +short
172.20.0.3
```

#### Broken

```
$ dig coredns @localhost -p 53054 A +short
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.11.4 (1.12.0 is also broken)
- Corefile: (as above)
- logs, if applicable:

```
coredns_working  | [INFO] 172.20.0.1:50609 - 28583 "A IN coredns. udp 48 false 1232" NOERROR qr,rd,ra 48 0.000462079s
coredns          | [INFO] 172.20.0.1:50574 - 31747 "A IN coredns. udp 48 false 1232" NOERROR qr,aa,rd 79 0.000182265s
```

- OS (e.g: `cat /etc/os-release`): Linux (Debian and Arch)
- Others:

**Comment by akhilsingh-git** [comment]
Can i work on this issue ?

**Comment by RealOrangeOne** [comment]
I'm not, and doesn't look like anyone else is - so go right ahead!

**Comment by akhilsingh-git** [comment]
Can you assign it to me ?

**Comment by akhilsingh-git** [comment]
Fix forwarding to Docker’s internal DNS in CoreDNS 1.11.4+ (Issue #7009).

**Comment by kamaladafrica** [comment]
Any news on this?

**Comment by apollo13** [comment]
I have debugged this a bit and as far as I can tell something happened with the container builds between 1.11.3 and 1.11.4. Putting a newly built coredns into the 1.11.3 container and it works even on current master but if I put the same executable into an 1.11.4 container it breaks. What stands out is that debian got upgraded from 11 to 12 in that time…

**Comment by johnbelamaric** [comment]
I think we updated to a new Debian image.

**Comment by johnbelamaric** [comment]
Oh...yes, you already mentioned that 🤦‍♂️. 

Yeah, maybe there is some delta there that matters.

**Comment by RealOrangeOne** [comment]
I actually think this might be a feature, not a bug (as the best bugs are).

The change which broke my example is actually bf38e4dbd9e5ca2f002f901fad386d97c80b42ce. When the base image was changed, the CWD was changed accidentally to `/home/nonroot`. In 1.11.4, the above commit was merged, moving the default back to `/`, and so my above example doesn't actually load the config, and thus doesn't work. Changing the `1.11.4` container to mount its config to `/Corefile` works just fine, as does removing `WORKDIR` from the container.

I think 1.11.4 is working correctly now, as most examples assume `/Corefile` as the configuration file. If anything, an improvement would be to either fail if no config file is found, or changing the default container to explicitly use `/Corefile` for configuration, or at least display which file is being used on startup. 

If changing the args to `/Corefile` is ok, I can get a PR opened.

**Comment by weiluntong** [comment]
Sorry @RealOrangeOne, I'm not here to help, just be a bother. I'm trying to follow along to see if I can get a usable 1.12.2 container.

I see the change made that added `WORKDIR` to the dockerfile.

I'm just a little lost on the `/Corefile` you're talking about (I'm also very new to CoreDNS and DNS applications in general). Do you mean to just change `/home/nonroot/Corefile` to `/Corefile` in the `compose.yml`?

**Comment by polarathene** [comment]
> Do you mean to just change `/home/nonroot/Corefile` to `/Corefile` in the `compose.yml`?

Yes, did you try it? CoreDNS checking for the config relative to the WORKDIR. Create/mount your Corefile config at the root `/` of the container filesystem.

---

I have a `compose.yaml` example [here](https://github.com/docker-mailserver/docker-mailserver/issues/3520#issuecomment-1700191973) which at the link you can see I integrate with separate `compose.yaml` for connecting/testing with other containers DNS:

```yaml
name: dns-example

networks:
  default:
    name: test-network
    ipam:
      driver: default
      config:
        - subnet: "172.20.42.0/24"

services:
  dns-server:
    image: coredns/coredns:1.12.1
    working_dir: /
    networks:
      default:
        ipv4_address: 172.20.42.10
    configs:
      - source: dns-config
        target: /Corefile
      - source: dns-zone-ptr
        target: /zones/example-rdns.zone
      - source: dns-zone-example
        target: /zones/example-internal.zone

configs:
  dns-config:
    content: |
      # CoreDNS will respond to any reverse DNS queries:
      in-addr.arpa {
        log
        file /zones/example-rdns.zone in-addr.arpa.
      }
      # As well as any DNS queries to `*.example.internal`:
      example.internal {
        log
        file /zones/example-internal.zone example.internal.
      }

      # Delegate queries belonging to these domains to
      # Docker's embedded DNS to resolve to container IP addresses:
      # NOTE: When using `docker compose run`, network aliases are not assigned to the container/DNS,
      # unless explicitly opting in for the container to add those.
      remote.test, example.test {
        log
        forward . 127.0.0.11
      }

      # If you need any other requests to go to public DNS:
      #. {
      #  log
      #  forward . 1.1.1.1
      #}

  # NOTE: `$$` is required to escape `$` from ENV interpolation (Docker Compose feature)
  dns-zone-ptr:
    content: |
      $$TTL 60
      $$ORIGIN 42.20.172.in-addr.arpa.

      @ SOA ns.example.internal. admin.example.internal. 2025102030 4h 1h 14d 10m

      ; Optional - The DNS and DMS containers don't really need PTR records:
      10 PTR dns-server.example.internal.
      20 PTR mail.example.test.

      30 PTR mail.remote.test.      ; Docker's embedded DNS (127.0.0.11) should have an entry with this IP assigned to the container of this FQDN (hostname).
      40 PTR mail.example.test.     ; This will not resolve back to the same client container IP (the FQDN instead resolves to the IP of the DMS container).
      50 PTR fail.example.internal. ; A valid DNS zone is queried, but there is no `A` record to verify the client IP (NXDOMAIN, non-existent domain).
      60 PTR fail.internal.         ; There is no DNS Zone for `fail.internal`, thus a DNS query will receive no response (timeout, similar to a temporary network error).

      ; Commented out this record to demonstrate what happens when a `PTR` record is missing:
      ; (Otherwise this would be the same as 172.20.42.30, except resolve via CoreDNS instead of Docker)
      ;70.42.20.172.in-addr.arpa. PTR valid.example.internal.

  dns-zone-example:
    content: |
      $$TTL 60
      $$ORIGIN example.internal.

      @ SOA ns.example.internal. admin.example.internal. 2025102030 4h 1h 14d 10m

      ; The IP assigned doesn't need to be valid, but a valid A/MX record is required for passing the restriction `reject_unknown_sender_domain`
      @                       A 172.20.42.10
      ; The primary nameserver referenced by SOA records identify the IP of the authoritative DNS server (the CoreDNS container)
      ns                      A 172.20.42.10
      valid.example.internal. A 172.20.42.70
```

The example above also shows forwarding to Docker's internal DNS is working (_as the linked comment demonstrates_).
