### ISSUE TITLE
Intermittent DNS Resolution Failures with CoreDNS v1.11.3 in Kubernetes Cluster - Resolved Temporarily by Pod Restarts

### ISSUE THREAD

**Issue by nitindhiman314e** [miekg/coredns#7212]
I'm experiencing intermittent DNS resolution failures in some pods within a Kubernetes cluster using CoreDNS version v1.11.3 (image: registry.k8s.io/coredns/coredns:v1.11.3). The issue is temporarily resolved by restarting the affected pods, but it reoccurs over time. I'm seeking assistance to diagnose and permanently resolve this problem.

**Environment:**

CoreDNS Version: v1.11.3 (image: registry.k8s.io/coredns/coredns:v1.11.3)
Kubernetes Version: Server Version: v1.32.1
Cluster Environment: BareMetal Server (IO Flood)
Operating System: Ubuntu 24.04.2 LTS
Kernel Version: 6.8.0-54-generic
Number of CoreDNS Replicas: 2

**CoreDNS ConfigMap:**

Here’s the current CoreDNS ConfigMap configuration deployed in the kube-system namespace:
text

```
.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30 {
       disable success cluster.local
       disable denial cluster.local
    }
    loop
    reload
    loadbalance
}
```

**Problem Description**:

Symptoms: Some pods in the cluster intermittently fail to resolve DNS queries (both internal, e.g., kubernetes.default.svc.cluster.local). The failures are not consistent across all pods or all times.

Temporary Fix: Restarting the affected pods (kubectl delete pod <pod-name>) resolves the issue temporarily, but it reappears after some time.

Impact: Applications relying on DNS resolution experience intermittent connectivity issues, disrupting normal operation.

Could you help identify potential causes of these intermittent DNS failures based on the provided configuration and symptoms?

**Comment by johnbelamaric** [comment]
First thing to check is whether traffic is actually getting to the pods. You can check the metrics (best starting point probably), enable query logging (big performance hit), enable tracing (can do sampling to reduce performance impact), or enable DNS tap (I think it has less impact than logging, but haven't tested that).

If traffic isn't getting to CoreDNS, then it's your networking stack.

If traffic is getting there, then we drill deeper. If you start with metrics, the "deeper" probably is to enable logging.

**Comment by chrisohaver** [comment]
Another thing to consider is whether or not you have [node local DNS cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) deployed.

If you do have it deployed, then you'll also want to check the node-local coredns instances deployed on each node.  Those instances are the first DNS hop from any pod making a DNS request.

If you don't have it deployed, then you should consider deploying it, since it was devised to mitigate intermittent DNS failures due to an underlying kernel network issue.

**Comment by nitindhiman314e** [comment]
Hi @johnbelamaric @chrisohaver - Thanks for your reply and suggestions! I appreciate it.

I’ve dug into this and replicated our production DNS issue to validate a fix, so here’s what I found and how it ties into your recommendations.

**Replication of the Production Issue:**
In production, we were seeing excessive NXDOMAIN queries in CoreDNS logs (e.g., test-service.314e.net), caused by the default `ndots:5` setting in pod /etc/resolv.conf. This led the resolver to append all search domains—including an extraneous 314e.net—before resolving the correct service name, increasing DNS load and causing delays. To investigate, I set up a test environment in the test-ns namespace.

Case 1: Default Configuration (ndots:5)
Pod Config:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-ns
  labels:
    app: test-app
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command: ['sh', '-c', 'while true; do nslookup test-service; sleep 1; done']
  dnsConfig:
    searches:
    - test-ns.svc.cluster.local
    - svc.cluster.local
    - cluster.local
    - local
    - 314e.net
```

**Observed Logs:**
```
2025-03-21T05:55:41.092+05:30 [INFO] 10.0.0.187:41581 - 6794 "A IN test-service.test-ns.svc.cluster.local. udp 56 false 512" NOERROR qr,aa,rd 110 0.000090905s
2025-03-21T05:55:41.092+05:30 [INFO] 10.0.0.187:41581 - 6795 "A IN test-service.svc.cluster.local. udp 48 false 512" NXDOMAIN qr,aa,rd 141 0.000093322s
2025-03-21T05:55:41.092+05:30 [INFO] 10.0.0.187:41581 - 6796 "A IN test-service.cluster.local. udp 44 false 512" NXDOMAIN qr,aa,rd 137 0.000048s
2025-03-21T05:55:41.092+05:30 [INFO] 10.0.0.187:41581 - 6801 "AAAA IN test-service.local. udp 36 false 512" NXDOMAIN qr,aa,rd,ra 111 0.000111206s
```
**Analysis:** The logs confirm multiple NXDOMAIN queries for invalid domains due to ndots:5. Since test-service has fewer than 5 dots, the resolver tried all search domains, replicating the production issue.


**Case 2: Setting ndots:1**

Updated Pod Config:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-ns
  labels:
    app: test-app
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command: ['sh', '-c', 'while true; do nslookup test-service; sleep 1; done']
  dnsConfig:
    searches:
    - test-ns.svc.cluster.local
    - svc.cluster.local
    - cluster.local
    - local
    - 314e.net
    options:
    - name: ndots
      value: "1"
```

**Observed Logs:**

```
2025-03-21T08:31:33.357+05:30 [INFO] 10.0.0.148:57573 - 35002 "A IN test-service.test-ns.svc.cluster.local. udp 56 false 512" NOERROR qr,aa,rd 110 0.000074804s
2025-03-21T08:31:34.362+05:30 [INFO] 10.0.0.148:56921 - 2156 "AAAA IN test-service.test-ns.svc.cluster.local. udp 56 false 512" NOERROR qr,aa,rd 149 0.000079799s
```

**Analysis:** With ndots:1, only NOERROR responses appeared for test-service.test-ns.svc.cluster.local. The resolver appended the first search domain, found a match, and stopped—eliminating NXDOMAIN errors and reducing query load.


Could you please suggest the below queries:

1. Do we need to update ndots:1 in all our pod configurations under /etc/resolv.conf?
**Context:** My tests showed ndots:1 eliminates unnecessary NXDOMAIN queries, but manually updating every pod spec is impractical. Is there anyway to do it via coredns configuration?

2. Do we need to use a single valid service URL in /etc/resolv.conf instead of multiple search domains?
**Context:** Reducing search domains to just <namespace>.svc.cluster.local worked in my tests, avoiding extra queries like 314e.net. Should we standardize on a single search domain across all namespaces to simplify DNS resolution, or do we need multiple domains for compatibility with existing apps?

3. How should we handle existing pods to apply ndots:1 without downtime?
**Context:** New pods can adopt ndots:1 via configuration, but existing pods need recreation. Can we automate this with rolling restarts for Deployments?

Thanks.
